services:

    # Database
    mysql-database-app:
        build:
            context: ./mysql
            dockerfile: ./Dockerfile
            args: 
                - DATABASE_NAME=image_management
                - DATABASE_USER_ROOT_PASSWORD=123
        container_name: mysql-database  
        volumes:
            - mysql-database-volume-app:/var/lib/mysql
        networks:
            - this-project-network  

    # Frontend 
    frontend-app:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile  
            args: 
                - DOMAIN_BACKEND=http://localhost:6600
                - DOMAIN_BACKEND_API=http://localhost:6600/api
                - DOMAIN_BACKEND_STATIC=http://localhost:6600/statics
        container_name: frontend  
        networks:
            - this-project-network

    # Backend
    backend-app: 
        build:
            context: ./backend
            dockerfile: ./Dockerfile
            args: 
                - DATABASE_HOST_NAME=mysql-database
                - DATABASE_HOST_PORT=3306
                - DATABASE_USER=root
                - DATABASE_PASSWORD=123
                - DATABASE_NAME=image_management
                - PATH_STATIC=../usr/src/my-app-name
        container_name: backend 
        volumes:
            - static-storage-volume-app:/usr/src/my-app-name
        networks:
            - this-project-network
  
    # Proxy
    proxy-app:
        build:
            context: ./proxy
            dockerfile: ./Dockerfile 
        container_name: proxy 
        networks:
            - this-project-network
        ports:
            - "6600:80"


volumes:
    mysql-database-volume-app:
    static-storage-volume-app:

networks:
    this-project-network:
        # driver: bridge